### ISSUE TITLE
How to load a custom YOLOv9 model using torch.hub.load()?

### ISSUE THREAD

**Issue by dsbyprateekg** [pytorch/hub#343] opened 2024-03-22 10:05 UTC
Hi,

I have trained a YOLOV9-e model on a custom dataset from this repo: [https://github.com/WongKinYiu/yolov9](url)

Now I tried to load it as below-
![image](https://github.com/pytorch/hub/assets/30830541/cc93dba0-e4be-4ebf-a9f4-b486f3209510)

But getting the following error-
![image](https://github.com/pytorch/hub/assets/30830541/b5ab21dd-f839-4b54-bf0f-c01ecbcf5ae2)

It says- `RuntimeError: Cannot find callable best.pt in hubconf`

Please share the correct way to load the model.

**Comment by NicolasHug** [comment] 2024-03-22 10:28
@dsbyprateekg sorry I'm not sure how to help here since the original code snippet you used wasn't shared. I'm seeing a reference to `best.pt` in the link you shared:

https://github.com/WongKinYiu/yolov9/blob/519346bd88c4e735e5ce9dc4c1a41c7033cc7402/hubconf.py#L8C1-L8C66


so I assume there is either something within that repo (in which case you need to address the issue there), or in your own code (in which case please share a minimal reproducing example).

I'll close the issue for now but feel free to reopen or follow-up

**Closed by NicolasHug** 2024-03-22 10:28 UTC
