### ISSUE TITLE
demo not working for Translation: TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by wise-east** [pytorch/hub#237] opened 2021-09-13 21:52 UTC
The example that I am trying to execute is: https://pytorch.org/hub/pytorch_fairseq_translation/

Whether it be in a local environment or Google Colab, I get the error: 
```
----> 1 en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')


7 frames
/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/criterions/__init__.py in <module>()
     22     CRITERION_DATACLASS_REGISTRY,
     23 ) = registry.setup_registry(
---> 24     "--criterion", base_class=FairseqCriterion, default="cross_entropy"
     25 )
     26 

TypeError: cannot unpack non-iterable NoneType object
```

Steps to replicate: 
open the google colab page linked to the tutorial at https://pytorch.org/hub/pytorch_fairseq_translation/ and execute the code.

**Comment by NicolasHug** [comment] 2021-09-14 08:19
Thanks for the report @wise-east , this notebook has indeed been broken for a while.

I also noticed that a few dependencies were missing: `pip install hydra-core omegaconf bitarray`.

@myleott since you authored the original file in https://github.com/pytorch/hub/pull/34, would you mind taking a look at this? Thanks!

**Comment by wise-east** [comment] 2021-09-15 06:06
@dianaml0 @NicolasHug  Thank you!

**Comment by AyushiNM** [comment] 2021-09-17 07:21
@dianaml0 @NicolasHug Is there any immediate solution for this? I'm trying to execute code in [this](https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/pytorch_fairseq_roberta.ipynb) notebook (provided by PyTorch), and I have the same error. Thank you.

**Comment by dianaml0** [comment] 2021-09-17 18:38
I am unable to reproduce the issue right now, @AyushiNM @wise-east are you still seeing these errors if you update the missing dependencies? (#239 )

**Comment by wise-east** [comment] 2021-09-17 23:19
@dianaml0 it worked after including the new dependencies. I thought I had tried it with the new dependencies except for `omegaconf`, but maybe that was the missing piece? Anyways, thank you for looking into this.

**Comment by NicolasHug** [comment] 2021-09-20 15:36
Thanks @dianaml0 , indeed it looks like something was fixed on the main branch of the fairseq repo.

I merged the PR as it seems that the colab notebook runs properly now (I checked myself as well).

I tried to re-enable the fairseq-translation tests which are currently skipped, but got a torch error which is probably unrelated https://app.circleci.com/pipelines/github/pytorch/hub/1342/workflows/65d1b468-787c-45de-bbe5-87840cc8c5e5/jobs/1777 (looks like the machine somehow believed it didn't have GPUs....)

I'll try to investigate this in the future but since the notebook seems to be running, I'll close this issue.
Thanks!

**Closed by NicolasHug** 2021-09-20 15:36 UTC
